<a href="https://colab.research.google.com/github/Arminismus/Deep-Learning-EXPS/blob/main/Linear_Regression_Student_Test_Score_Prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np

import matplotlib.pyplot as plt

from tensorflow.keras.layers import Dense,Normalization

from tensorflow.keras import Sequential
import pandas as pd

In [ ]:
#import dataset:

#Student Test Score prediction:
data = pd.read_csv('/content/test_scores.csv')


In [ ]:
data

school school_setting school_type classroom teaching_method  n_student  \
0     ANKYI          Urban  Non-public       6OL        Standard       20.0   
1     ANKYI          Urban  Non-public       6OL        Standard       20.0   
2     ANKYI          Urban  Non-public       6OL        Standard       20.0   
3     ANKYI          Urban  Non-public       6OL        Standard       20.0   
4     ANKYI          Urban  Non-public       6OL        Standard       20.0   
...     ...            ...         ...       ...             ...        ...   
2128  ZOWMK          Urban      Public       ZBH        Standard       30.0   
2129  ZOWMK          Urban      Public       ZBH        Standard       30.0   
2130  ZOWMK          Urban      Public       ZBH        Standard       30.0   
2131  ZOWMK          Urban      Public       ZBH        Standard       30.0   
2132  ZOWMK          Urban      Public       ZBH        Standard       30.0   

     student_id  gender                             lunch  pretest  posttest  
0         2FHT3  Female                  Does not qualify     62.0      72.0  
1         3JIVH  Female                  Does not qualify     66.0      79.0  
2         3XOWE    Male                  Does not qualify     64.0      76.0  
3         556O0  Female                  Does not qualify     61.0      77.0  
4         74LOE    Male                  Does not qualify     64.0      76.0  
...         ...     ...                               ...      ...       ...  
2128      T8LSK  Female                  Does not qualify     39.0      55.0  
2129      VNP26  Female  Qualifies for reduced/free lunch     38.0      46.0  
2130      YDR1Z  Female  Qualifies for reduced/free lunch     45.0      51.0  
2131      YUEIH    Male  Qualifies for reduced/free lunch     46.0      53.0  
2132      ZVCQ8    Male  Qualifies for reduced/free lunch     41.0      48.0  

[2133 rows x 11 columns]

In [ ]:
data.drop('school',inplace = True,axis = 1)

In [ ]:
data.drop(['classroom','student_id'],inplace = True,axis = 1)
overhead = data

In [ ]:
def one_hot_encode(data,feature_values,feature):
  for value in feature_values:
    data[value] = (data[feature] == value)
    #make new values into ints:
    data[value] = data[value].replace({True:1,False:0})
  
  #remove original feature
  data.drop(feature,inplace = True,axis = 1)

In [ ]:
s = set()
for i in overhead['teaching_method']:
  if i not in s:
    s.add(i)
list(s)

['Experimental', 'Standard']

In [ ]:
feature = 'teaching_method'
feature_values = ['Experimental','Standard']

def find_values(data,feature):
  s = set()
  for i in data[feature]:
    if i not in s:
      s.add(i)
  return list(s)

feature_values = find_values(feature= 'teaching_method',data = overhead)

In [ ]:
one_hot_encode(data = overhead,feature = 'school_setting',feature_values = find_values(overhead,'school_setting'))

In [ ]:
one_hot_encode(data = overhead,feature = 'teaching_method',feature_values = feature_values)

In [ ]:
one_hot_encode(data = overhead,feature = 'gender',feature_values = find_values(overhead,'gender'))

In [ ]:
overhead.drop('Male',inplace = True,axis = 1)

In [ ]:
one_hot_encode(data = overhead,feature = 'lunch',feature_values = find_values(overhead,'lunch'))

In [ ]:
overhead.drop('Does not qualify',inplace = True,axis = 1)

In [ ]:
overhead

school_type  n_student  pretest  posttest  Suburban  Rural  Urban  \
0     Non-public       20.0     62.0      72.0         0      0      1   
1     Non-public       20.0     66.0      79.0         0      0      1   
2     Non-public       20.0     64.0      76.0         0      0      1   
3     Non-public       20.0     61.0      77.0         0      0      1   
4     Non-public       20.0     64.0      76.0         0      0      1   
...          ...        ...      ...       ...       ...    ...    ...   
2128      Public       30.0     39.0      55.0         0      0      1   
2129      Public       30.0     38.0      46.0         0      0      1   
2130      Public       30.0     45.0      51.0         0      0      1   
2131      Public       30.0     46.0      53.0         0      0      1   
2132      Public       30.0     41.0      48.0         0      0      1   

      Experimental  Standard  Female  Qualifies for reduced/free lunch  
0                0         1       1                                 0  
1                0         1       1                                 0  
2                0         1       0                                 0  
3                0         1       1                                 0  
4                0         1       0                                 0  
...            ...       ...     ...                               ...  
2128             0         1       1                                 0  
2129             0         1       1                                 1  
2130             0         1       1                                 1  
2131             0         1       0                                 1  
2132             0         1       0                                 1  

[2133 rows x 11 columns]

In [ ]:
overhead.rename(columns = {'Qualifies for reduced/free lunch':'Free Lunch'},inplace = True)

In [ ]:
overhead

school_type  n_student  pretest  posttest  Suburban  Rural  Urban  \
0     Non-public       20.0     62.0      72.0         0      0      1   
1     Non-public       20.0     66.0      79.0         0      0      1   
2     Non-public       20.0     64.0      76.0         0      0      1   
3     Non-public       20.0     61.0      77.0         0      0      1   
4     Non-public       20.0     64.0      76.0         0      0      1   
...          ...        ...      ...       ...       ...    ...    ...   
2128      Public       30.0     39.0      55.0         0      0      1   
2129      Public       30.0     38.0      46.0         0      0      1   
2130      Public       30.0     45.0      51.0         0      0      1   
2131      Public       30.0     46.0      53.0         0      0      1   
2132      Public       30.0     41.0      48.0         0      0      1   

      Experimental  Standard  Female  Free Lunch  
0                0         1       1           0  
1                0         1       1           0  
2                0         1       0           0  
3                0         1       1           0  
4                0         1       0           0  
...            ...       ...     ...         ...  
2128             0         1       1           0  
2129             0         1       1           1  
2130             0         1       1           1  
2131             0         1       0           1  
2132             0         1       0           1  

[2133 rows x 11 columns]

In [ ]:
one_hot_encode(data = overhead,feature = 'school_type',feature_values = find_values(overhead,'school_type'))

In [ ]:
overhead.drop('Non-public',inplace = True,axis = 1)

In [ ]:
y = overhead.pop('posttest').to_numpy()

In [ ]:
overhead = overhead.to_numpy()

In [ ]:
y

array([72., 79., 76., ..., 51., 53., 48.])

In [ ]:
#let's Create our Neural Network: No test set
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(overhead,y,test_size = 0.2,random_state = 12)


In [ ]:
x_train

array([[17., 84.,  0., ...,  1.,  0.,  0.],
       [14., 57.,  0., ...,  0.,  0.,  0.],
       [25., 35.,  0., ...,  1.,  1.,  1.],
       ...,
       [23., 66.,  1., ...,  1.,  0.,  1.],
       [20., 54.,  0., ...,  1.,  1.,  0.],
       [30., 30.,  0., ...,  0.,  1.,  1.]])

In [ ]:
y_test

array([ 68.,  70.,  74.,  56.,  68.,  80.,  70.,  56.,  46.,  63.,  78.,
        41.,  77.,  52.,  75.,  87.,  53.,  91.,  68.,  88.,  75.,  52.,
        54.,  58.,  48.,  46.,  60.,  95.,  81.,  43.,  82.,  54.,  57.,
       100.,  86.,  47.,  55.,  57.,  62.,  38.,  45.,  91.,  55.,  82.,
        74.,  84.,  66.,  60.,  79.,  67.,  67.,  93.,  66.,  77.,  72.,
        46.,  61.,  76.,  61.,  42.,  90.,  51.,  82.,  57.,  58.,  70.,
        61.,  54.,  88.,  69.,  66.,  54.,  69.,  72.,  57.,  56.,  71.,
        83.,  51.,  56.,  60.,  58.,  46.,  67.,  55.,  48.,  67.,  66.,
        71.,  81.,  60.,  76.,  55.,  48.,  73.,  62.,  91.,  92.,  82.,
        42.,  71.,  82.,  56.,  51.,  52., 100.,  59.,  77.,  78.,  68.,
        65.,  78.,  93.,  67.,  80.,  78.,  88.,  46.,  76.,  48.,  88.,
        74.,  73.,  72.,  42.,  75.,  59.,  51.,  84.,  81.,  77.,  49.,
        81.,  55.,  75.,  69.,  93.,  77.,  73.,  58.,  49.,  95.,  61.,
        68.,  67.,  85.,  50.,  82.,  58.,  78.,  7

In [ ]:
#let's make the model and compile and fit it:
model = Sequential([
    Normalization(input_shape =(10,)),
    Dense(units = 14,activation = 'relu'),
    Dense(units = 3,activation = 'relu'),
    Dense(units = 1,activation = 'linear'),
])

In [ ]:
model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 normalization_7 (Normalizat  (None, 10)               21        
 ion)                                                            
                                                                 
 dense_16 (Dense)            (None, 14)                154       
                                                                 
 dense_17 (Dense)            (None, 3)                 45        
                                                                 
 dense_18 (Dense)            (None, 1)                 4         
                                                                 
Total params: 224
Trainable params: 203
Non-trainable params: 21
_________________________________________________________________


In [ ]:
model.compile(optimizer = tf.keras.optimizers.Adam(learning_rate=0.01),loss = 'mse',metrics=['accuracy'])

In [ ]:
#make the Pandas dataframe into a vector
model.fit(x_train,y_train,epochs = 200)

Epoch 1/200
54/54 [==============================] - 1s 2ms/step - loss: 2111.6606 - accuracy: 0.0000e+00
Epoch 2/200
54/54 [==============================] - 0s 2ms/step - loss: 49.4966 - accuracy: 0.0000e+00
Epoch 3/200
54/54 [==============================] - 0s 2ms/step - loss: 27.7705 - accuracy: 0.0000e+00
Epoch 4/200
54/54 [==============================] - 0s 2ms/step - loss: 19.9856 - accuracy: 0.0000e+00
Epoch 5/200
54/54 [==============================] - 0s 2ms/step - loss: 17.6142 - accuracy: 0.0000e+00
Epoch 6/200
54/54 [==============================] - 0s 2ms/step - loss: 15.6134 - accuracy: 0.0000e+00
Epoch 7/200
54/54 [==============================] - 0s 2ms/step - loss: 14.8783 - accuracy: 0.0000e+00
Epoch 8/200
54/54 [==============================] - 0s 2ms/step - loss: 14.2147 - accuracy: 0.0000e+00
Epoch 9/200
54/54 [==============================] - 0s 2ms/step - loss: 13.6406 - accuracy: 0.0000e+00
Epoch 10/200
54/54 [==============================] - 0s 2ms/s

In [ ]:
n = 0
model.predict(x_test[n]),y_test[n]

(array([[78.87812]], dtype=float32), 80.0)

In [ ]:
model.evaluate(x_test,y_test)

14/14 [==============================] - 0s 3ms/step - loss: 13.1502 - accuracy: 0.0000e+00


[13.150179862976074, 0.0]

In [ ]:
x_test[1]

array([27., 63.,  1.,  0.,  0.,  0.,  1.,  1.,  0.,  1.])

In [ ]:
model.predict([27,63,1,0,0,0,1,1,0,1])

array([[467.20676]], dtype=float32)