<a href="https://colab.research.google.com/github/Arminismus/Deep-Learning-EXPS/blob/main/Simple_Denoising.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from tensorflow.keras import Sequential

from tensorflow.keras.layers import Dense,Normalization
import numpy as np
import pandas as pd

In [4]:
#let's Create the Artificial Data: Clean: One hot vectors  Noisy: Add noise to one hot vector

#ALL one hot 20 dimensional vectors:
vecs = [[1 if i==j else 0for i in range(20)] for j in range(20)]

In [6]:
vecs = np.array(vecs)

In [15]:
#Now let's create a data set where we sample one vector randomly:
dataset = []
for _ in range(1999):
  dataset.append(vecs[np.random.randint(0,19)])


In [22]:
noisy_dataset = [[entry + (1e-3)*np.random.uniform() for entry in data] for data in dataset]

In [79]:
x = np.array(noisy_dataset)
y = np.array(dataset)

In [126]:
#let's make the model:
model = Sequential([
    tf.keras.Input(shape=(20,)),
    Dense(units = 20,activation = 'sigmoid'),
    Dense(units = 20,activation = 'sigmoid'),
])

In [113]:
model.summary()

Model: "sequential_11"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_44 (Dense)            (None, 1)                 21        
                                                                 
 dense_45 (Dense)            (None, 20)                40        
                                                                 
Total params: 61
Trainable params: 61
Non-trainable params: 0
_________________________________________________________________


In [134]:
model.compile(optimizer = tf.keras.optimizers.Adam(learning_rate = 0.01),loss = 'mse')

In [83]:
y[0],x[0]

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0]),
 array([7.89026025e-04, 6.10136583e-04, 5.72283659e-04, 5.03008844e-04,
        7.07522959e-04, 8.68488202e-04, 8.16921451e-04, 3.25233846e-04,
        5.49436427e-04, 9.33460799e-04, 3.63355233e-04, 8.63599919e-04,
        4.15465864e-04, 3.33465528e-04, 6.64514092e-04, 4.10842789e-04,
        1.00074899e+00, 9.62985221e-04, 9.00541239e-04, 4.21472864e-04]))

In [135]:
model.fit(x,y,epochs = 200)

Epoch 1/200
63/63 [==============================] - 15s 927us/step - loss: 8.7742e-08
Epoch 2/200
63/63 [==============================] - 0s 971us/step - loss: 8.6048e-08
Epoch 3/200
63/63 [==============================] - 0s 928us/step - loss: 8.3733e-08
Epoch 4/200
63/63 [==============================] - 0s 937us/step - loss: 8.1086e-08
Epoch 5/200
63/63 [==============================] - 0s 925us/step - loss: 7.8271e-08
Epoch 6/200
63/63 [==============================] - 0s 966us/step - loss: 7.5388e-08
Epoch 7/200
63/63 [==============================] - 0s 939us/step - loss: 7.2505e-08
Epoch 8/200
63/63 [==============================] - 0s 942us/step - loss: 6.9678e-08
Epoch 9/200
63/63 [==============================] - 0s 965us/step - loss: 6.6922e-08
Epoch 10/200
63/63 [==============================] - 0s 968us/step - loss: 6.4262e-08
Epoch 11/200
63/63 [==============================] - 0s 946us/step - loss: 6.1724e-08
Epoch 12/200
63/63 [==============================]

In [49]:
x[0]

array([7.89026025e-04, 6.10136583e-04, 5.72283659e-04, 5.03008844e-04,
       7.07522959e-04, 8.68488202e-04, 8.16921451e-04, 3.25233846e-04,
       5.49436427e-04, 9.33460799e-04, 3.63355233e-04, 8.63599919e-04,
       4.15465864e-04, 3.33465528e-04, 6.64514092e-04, 4.10842789e-04,
       1.00074899e+00, 9.62985221e-04, 9.00541239e-04, 4.21472864e-04])

In [140]:
model.predict(np.array([[1+(1e-3*np.random.uniform()) if i == 2 else 1e-3*np.random.uniform() for i in range(20)]]))

array([[3.2008433e-05, 6.3322332e-05, 9.9975377e-01, 8.8447428e-05,
        4.9784241e-05, 3.2730419e-05, 4.5603902e-06, 4.3264808e-05,
        9.4471274e-05, 1.0240403e-04, 3.2207521e-11, 1.4957786e-04,
        3.3601173e-06, 1.5623166e-06, 7.1522954e-05, 4.1958187e-06,
        4.9103357e-05, 4.4608347e-05, 1.1522470e-04, 2.8075969e-05]],
      dtype=float32)

In [139]:
#We successfuly trained The model! Lessons Learned: 1. The mae is unsuited for this task, since it get stuck in a minimum. 2. mse is good. 3. The architecture, contrary to my
#belief, should not be that of an auto-encoder, but a completely paralell network works.(larger networks should then work.) 4.The denoising in an autoencdoer is because of dimensionality reduction, and 
#in our example, dimensionality reduction only leads to the loss of data.

[[678.9819040149731,
  519.1750916613865,
  28.640397872071397,
  23.018406116283142,
  579.1598331988354,
  596.9047062356655,
  830.6658752909217,
  632.5620273219746,
  714.5449506124799,
  430.58243576112756,
  403.8115293571163,
  712.3871651321175,
  172.13740890457973,
  440.3458073457223,
  164.3379760028908,
  542.5222997255338,
  154.45543647139993,
  176.78602899645978,
  407.4412542011785,
  650.3673745370821]]